version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    environment:
      - PORT=${BACKEND_PORT}
      - NODE_ENV=production
      - smtp_email=pulkits117@gmail.com
      - smtp_password="dtms jubi ijmf khpa"
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - PORT=${FRONTEND_PORT}
      - BACKEND_URL=${BACKEND_URL}
    ports:
      - "80:5173"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
